### ISSUE TITLE
Static Site

### ISSUE THREAD

**Issue by dandevri** [Rowin206/DatingApp#1]
Start working on your interface!

* Create a sitemap of all the relevant pages of your feature. You can use google drawings or omnigraffle to create an overview
* Sketch some wireframes (or wireflows) of the interface. These can be rough sketches or more hi-fi. Find a fidelity that suits you.
* Turn your wireflow into static HTML pages. Do a HTML breakdown of your wireframe to see which semantic HTML elements you need. Ten create the HTML page for your feature.
* Add some presentational CSS. You've already done some branding research so you're already able to set-up some basic styles. Think about colors, fonts etc.

**Comment by Rowin206** [comment]
Thank you for the feedback, I updated my wiki. You can find it under "week 2, 3 and 4". I have to say, to make it more concrete, it helped me to keep a clear overview.
