### ISSUE TITLE
Job Stories

### ISSUE THREAD

**Issue by dandevri** [Rowin206/DatingApp#2]
Which Job Story are you going to work on? Your Job Stories are too generic. Based on your wiki you want to do something based on location or dog tags? I'm not quite sure how that supposed to work, that's also because I don't see any interface of some sort.

The dog tag system seems interesting but what is the focus group for that? Who is specifically looking for a dating app that matches based on tags? Try to clearly define that.

**Comment by Rowin206** [comment]
Thank you for the feedback, I updated my wiki. You can find it under "week 4"
